### ISSUE TITLE
DB weakly-held object does not exist in server

### ISSUE THREAD

**Issue by dladams** [LSSTDESC/desc-prod#11]
I see errors like this in the DESCprod service:
<pre>
Traceback (most recent call last):
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/dev/desc-prod/server/app.py", line 330, in home
    jtab = JobTable(udat.descname)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/descprod/job_table.py", line 13, in __init__
    self.refresh()
  File "/home/descprod/conda/lib/python3.11/site-packages/descprod/job_table.py", line 16, in refresh
    self.jobs, self.error_message = JobData.get_jobs_from_db(self.descname)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/descprod/jobs.py", line 153, in get_jobs_from_db
    for row in cur.fetchall():
               ^^^^^^^^^^^^^^^
  File "/home/descprod/conda/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 610, in fetchall
    if not self._cnx.unread_result:
           ^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
</pre>

**Comment by dladams** [comment]
I believe this is occurs when a function creates a connection, executes a query to generate a cursor, returns the cursor and then the caller uses the cursor to look at query results after the connection has been deleted. A rookie python mysql mistake. 

The method JobData.db_query tries to protect against this by naming the connection 'query' and saving it in a dict but the name is always 'query' and so there may be conflicts with multiple users.

I fixed this by always returning and holding the connection with the cursor.
