### ISSUE TITLE
Version 0.3

### ISSUE THREAD

**Issue by dladams** [LSSTDESC/desc-prod#2]
The last version tag was 0.2.56. We now begin version 0.3 with goals described in [Jan 25 talk at the DESC CO meeting](https://drive.google.com/file/d/1uAMfWpQLenxF_50mjmBWqISEEDxOkdrc/view?usp=share_link). The major goal is to enable users to start jobs on NERSC machines (including perlmutter batch and login nodes) by running an agent which has their NERSC credentials.

**Comment by dladams** [comment]
Our first use case is to specify a job in the SPIN UI (descprod.com) and have the user start an agent on a perlmutter login node. For this (and most other use cases), the agent will fetch the data for a job, start the job and send back results and updates. The JobData class has been modified to put this persistent data into a map for each job object. This is  tag 0.1.

**Comment by dladams** [comment]
We want the job data in a persistent DB. I added mysql-server to dockerfile-05 and built, pushed. I am able to start the service in SPIN descprod with
<pre>
service mysql start
</pre>
by hand for now.

The datadir for mysql is /var/lib/mysql which is not persistent (across server restarts). In the SPIN DESCprod service, I created a new volume dpvol03 with a directory mysql and copied the files from /var/lib/mysql there. I was not able to remove the latter and so I added a mount of dpvol/mysql over /var/lib/mysql.  After the server restart, I was able to create a DB/table descprod/jobdata. After another restart I verified that the DB and table still existed.

**Comment by dladams** [comment]
I added a start command mysql to start the mysql server in version 0.3.2. I also added this to the SPIN DESCprod service startup and verified that the service now starts with mysql running.

**Comment by dladams** [comment]
Trying to connect to the DB in python, I had this error:
<pre>
>>> import mysql.connector
>>> con = mysql.connector.connect(database='descprod')
Traceback (most recent call last):
  File "/home/descprod/conda/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 288, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Host '127.0.0.1' is not allowed to connect to this MySQL server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/descprod/conda/lib/python3.10/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/descprod/conda/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 118, in __init__
    self.connect(**kwargs)
  File "/home/descprod/conda/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1178, in connect
    self._open_connection()
  File "/home/descprod/conda/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 293, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1130 (HY000): Host '127.0.0.1' is not allowed to connect to this MySQL server
</pre>

I resolved it with:
<pre>
mysql> select User,host from mysql.user;
+------------------+-----------+
| User             | host      |
+------------------+-----------+
| debian-sys-maint | localhost |
| mysql.infoschema | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)

mysql> create user root@'127.0.0.1';
Query OK, 0 rows affected (0.01 sec)

mysql> GRANT ALL ON *.* to root@'127.0.0.1';
Query OK, 0 rows affected (0.12 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.01 sec)

mysql> select User,host from mysql.user;
+------------------+-----------+
| User             | host      |
+------------------+-----------+
| root             | 127.0.0.1 |
| debian-sys-maint | localhost |
| mysql.infoschema | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
6 rows in set (0.00 sec)
</pre>

**Comment by dladams** [comment]
On my laptop, I instead added user descprod:
<pre>
mysql> create user descprod@'127.0.0.1';
Query OK, 0 rows affected (0.08 sec)

mysql> GRANT ALL ON *.* to descprod@'127.0.0.1';
Query OK, 0 rows affected (0.04 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.02 sec)

mysql> select User,host from mysql.user;
+------------------+-----------+
| User             | host      |
+------------------+-----------+
| descprod         | 127.0.0.1 |
| debian-sys-maint | localhost |
| mysql.infoschema | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
6 rows in set (0.02 sec)
</pre>

**Comment by dladams** [comment]
Methods are added to check and optionally create a DB and table in that DB with default names "descprod" and "jobdata". The table schema includes that current identified for jobs with the index a primary key. there is also an option to drop the table. All in version 0.3.3.

**Comment by dladams** [comment]
After earlier dropping the jobdata table on SPIN, I create it with the new schema:
<pre>
root@descprod-66cccfcd5d-z2dn7:~# cd dev/desc-prod
root@descprod-66cccfcd5d-z2dn7:~/dev/desc-prod# cd server
root@descprod-66cccfcd5d-z2dn7:~/dev/desc-prod/server# python
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from descprod import JobData
>>> JobData.have_table()
False
>>> JobData.have_table(create_table=True)
JobData.have_table: Creating table jobdata
True
>>> 
</pre>

**Comment by dladams** [comment]
Class and object data and methods are added to JobData to enable a job to insert its data into a DB, track fields that have changes since a DB update and to set update values in the DB. All changes are in 0.3.4.

**Comment by dladams** [comment]
The wrapper is enhanced to add a heartbeat, i.e. poll the process at regular intervals (now 10 sec) and write the status to the wrapper json file. The job class reads this file when its return status, stop time or progress are read. The progress string is now a persistent data member and included in the DB schema.

**Comment by dladams** [comment]
I updated the service on SPIN.

Removing an old job, an exception was raised:
<pre>
  File "/home/descprod/dev/desc-prod/server/descprod/jobs.py", line 734, in delete

    shutil.rmtree(rundir)

  File "/home/descprod/conda/lib/python3.10/shutil.py", line 724, in rmtree

    _rmtree_safe_fd(fd, path, onerror)

  File "/home/descprod/conda/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd

    _rmtree_safe_fd(dirfd, fullname, onerror)

  File "/home/descprod/conda/lib/python3.10/shutil.py", line 680, in _rmtree_safe_fd

    onerror(os.unlink, fullname, sys.exc_info())

  File "/home/descprod/conda/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd

    os.unlink(entry.name, dir_fd=topfd)

FileNotFoundError: [Errno 2] No such file or directory: 'taskerr0010.log'
</pre>
 in jobs.py line 734 from rmtree:
<pre>
        if os.path.exists(rundir):
            shutil.rmtree(rundir)
</pre>
Removing other jobs, I saw other unexpected errors including "Archive command failed".  I suspect the filesystem is not fully updated from the opertaion on one line, when the next python line is executed.

To try to fix this, I added a loop check with delays (wait_for_path) after creating the archive and after deleting the run directory. Changes are in 0.3.6.

I updated the SPIN service and deleted four jobs without problems.

**Comment by dladams** [comment]
I could not open mysql on my laptop where default account is descprod. I change the disk config to use a persistent docker disk and restarted many times. I finally realize i have to use "-h 127.0.0.1" when starting the mysql CL utilityas descprod.

**Comment by dladams** [comment]
Jobs now update DB on creation, submission and running. Local progress is not working and remote progress has yet to be added. I added stups to fetch and update jobs from the server and verified I can access these with messages from requests.

**Comment by dladams** [comment]
The displayed job table is now read from the DB. Version 0.3.8

**Comment by dladams** [comment]
I had problems getting the new version running at NERSC because DB schema had changed. I finally used JobData.have_table to drop and then recreate DB. Now all appears fine there. Version is 0.3.11.

**Comment by dladams** [comment]
I fixed witing of job data to the DB to include wrapper info. And I added JobData.jmap() which returns a json map of the data for a job. Version is 0.3.12. Still need to test this at nersc.

**Comment by dladams** [comment]
Version 0.3.12 which is the first read and write all job data to mysql is now running at NERSC (as well as my laptop).

I did see one crash when the update map was transiently missing. I added a fix for that in 0.3.13.

**Comment by dladams** [comment]
Version 0.3.14 adds seconds to the time displayed in home page header and start time columns. Useful for meauring the time to refresh the table which is now (since the mysql switch) many seconds on my laptop an about a second at nersc. Something to keep an eye on.

**Comment by dladams** [comment]
For version, 0.3.15, the python support code in server/descprod is moved to ./descprod and setuptools interface added so we pip install the client parts of desc-prod. The package has to be installed and the client code should be useable outside the server env. A new image, version 06, is required to run the server.

**Comment by dladams** [comment]
For version 0.3.16, the server command get_job is fixed to return the job json map.
Also, command descprod-get-job is added to display that map.

**Comment by dladams** [comment]
For 0.3.17,  descprod-get-job is fixed and nicely formatted. It shows message for error and job description for success.
Also sdate is fixed so it always formats time in UTC.
Note that jobs cannot be fetched like this if they have not been loaded in the server.

**Comment by dladams** [comment]
For 0.3.18, add user name from env or command line in descprod-get-job.

**Comment by dladams** [comment]
For 0.3.19 to advance toward running remote jobs:
* Introduce job.usedb set in ctor (default true) which can be set false to have a JobData object disconnected from the DB. This is intended for use in client scripts.
* Revamp JobData to allow remote running. Add host and run directory to the DB job data. Run directory is specified in run method instead of ctor and the json config file in the run directory is created there.
* Add host and rundir to the job display.
* Created a new job table with the new schema from a python session:
<pre>
>>> descprod.JobData.db_table(drop_table=True, create_table=True)
JobData.db_table: Dropping table jobdata
JobData.db_table: Drop was successful.
JobData.db_table: Creating table jobdata
JobData.db_table: Create was successful.
True
</pre>
I did after restarting server and before before using the web service because it appears to leave connections open.
* Display port after PID in job table display.

**Comment by dladams** [comment]
For 3.20, continue work on start_jobs:
* Fix JobData.jmap_update to always return string.
* Add JobData.ready_to_run() that returns blank if ready.
* Drop command from DB data and change JobData.command() to evaluate it from jobtype and config.
* Add option to start a job (iff it is ready to run) in the job table menu.
* Add recording and display of session ID for each job.

**Comment by dladams** [comment]
For 3.21, toward using ptenv to set up for running parsltest:
* JobData.run sets up for server env iff rundir is missing
* Add pip install of ptenv utilities
* Add create of ptenv-home-00 to startup if missing but
* Add create of homeptenv00 to image version 7

**Comment by dladams** [comment]
For 3.22:
* Eliminate need to run ptenv-create twice when miniconda is absent.
* Add miniconda flavor for MacOSX so ptenv works on mac.
* Set ptenv python version to 3.11.0. Older version had conflicts with that one on my laptop.
* But finally give on on mac: workqueue and sysmon do not work there.

**Comment by dladams** [comment]
For 0.3.23:
* Modify jobs.py to use command runapp-parsltest to run parsltest.
* Fix getlogin in get_job.
* Stop running jobs with sudo so we can use pre-installed ptenv.

**Comment by dladams** [comment]
For 0.3.24 fis remote running and start implementing wrapper-server job communication:
* Drop setups of conda and parsl when starting jobs in runs.py. These only work on server.
* Drop bash -login option when starting jobs in jobs.py so we have the descprod commands.
* Modify descprod-wrapper to send update messages back to the server. Still need to ad check of reponse.

**Comment by dladams** [comment]
For 0.3.25, try to fix jobs failing on descprod server.
* Fix descprod-version. Version is now written to stdout.
* Drop sudo to descprod in start for root user.

Rebuild image (descprod-08) same as 07 except with desc-prod 0.3.25.

**Comment by dladams** [comment]
For 0.3.26, move toward sending job updates from remote to server.
* Implement update_job in app.py
* Add server url in start_job call to JobData.run
* Update start_job to pass server url to descprod-wrap
* Update descprod-wrap to send back messages to the received server if it is present.
* Update JobData.get_job and server get_job and and update_job calls to take job from DB if not already in cache.
* Modify JobData ctor to initialize update_time.
* Modify server to allow missing update time.
* Add host and update_time updates to wrapper.
* Fix rundir (replace run_directory) update in wrapper.
* Fix rc overwrite in wrapper

Job updates now working on davidmac (server and runner on my laptop).

**Comment by dladams** [comment]
For 0.3.27, get remote running working at NERSC :
* Deploy nerscprod server with version 0.3.26.
* Fix handling of unspecified server (default descprod) in JobData.run.
* Fix default server in wrapper.

I am now able to run nerscprod jobs on perlmutter login nodes.
I also ran a nerscprod job on my laptop (in linux window from descprod).

**Comment by dladams** [comment]
For 0.3.28, make job deletion more robust and verbose in log.
* Clean up job removal code.
* Make sure on delete removes everything: rundir, archive, DB entry, transient entries.
* Left justify job menu
* Move server_util() to utils.py and update get_job.py and start_job.py accordingly.

**Comment by dladams** [comment]
Next want to work on batch submission. This is discussed in #3 .
