### ISSUE TITLE
DB crashes

### ISSUE THREAD

**Issue by dladams** [LSSTDESC/desc-prod#6]
I have seen intermittent failures when first connecting or refreshing the DESCprod server page indicating a DB access problem. Here is an example:
<pre>
10.42.5.100 - - [10/Jul/2023 14:09:45] "GET /home HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/descprod/conda/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/descprod/dev/desc-prod/server/app.py", line 288, in home
    jtab = JobTable(udat.descname)
  File "/home/descprod/conda/lib/python3.10/site-packages/descprod/job_table.py", line 13, in __init__
    self.refresh()
  File "/home/descprod/conda/lib/python3.10/site-packages/descprod/job_table.py", line 16, in refresh
    self.jobs = JobData.get_jobs_from_db(self.descname)
  File "/home/descprod/conda/lib/python3.10/site-packages/descprod/jobs.py", line 145, in get_jobs_from_db
    cur = cls.db_query_where(f"descname='{descname}'", cols='id')
  File "/home/descprod/conda/lib/python3.10/site-packages/descprod/jobs.py", line 366, in db_query_where
    haveit = cls.db_table(tnam)
  File "/home/descprod/conda/lib/python3.10/site-packages/descprod/jobs.py", line 241, in db_table
    raise Exception(f"{myname}: Unable to connect to DB {dbnam}")
Exception: JobData.db_table: Unable to connect to DB descprod

**Comment by dladams** [comment]
I have not had DB problems for a while and am closing this. My fix in [this NERSC ticket](https://nersc.servicenowservices.com/sp?sys_id=548e07311b98f15059b0dc6ce54bcbc7&view=sp&id=ticket&table=incident) may be relevant.
